CREATE TABLE IF NOT EXISTS "iot_mqtt_server" (
     "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     "code" varchar NOT NULL,
     "endpoint" varchar,
     "port" int,
     "protocol" varchar,
     "creator" varchar DEFAULT '',
     "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "updater" varchar DEFAULT '',
     "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     "deleted" bit NOT NULL DEFAULT FALSE,
     "tenant_id" bigint NOT NULL,
     "app_id" varchar,
     "app_client_id" varchar,
     "app_client_secret" varchar,
     "app_username" varchar,
     "app_password" varchar,
     PRIMARY KEY ("id")
) COMMENT 'MQTT服务节点配置信息';

CREATE TABLE IF NOT EXISTS "iot_device_info" (
     "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
     "uni_code" varchar,
     "creator" varchar DEFAULT '',
     "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
     "updater" varchar DEFAULT '',
     "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     "deleted" bit NOT NULL DEFAULT FALSE,
     "tenant_id" bigint NOT NULL,
     "mqtt_server_id" bigint,
     "name" varchar,
     PRIMARY KEY ("id")
) COMMENT '设备信息';