--- #################### 数据库相关配置 ####################
spring:
  datasource:
    dynamic: # 多数据源配置
      primary: master
      datasource:
        master:
          url: jdbc:mysql://${MYSQL_MASTER_ADDR:192.168.1.200:3306}/${spring.datasource.dynamic.datasource.master.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
        slave: # 模拟从库，可根据自己需要修改
          url: jdbc:mysql://${MYSQL_SLAVE_ADDR:192.168.1.200:3306}/${spring.datasource.dynamic.datasource.slave.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例

  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: ${REDIS_HOST:192.168.1.200}
    database: 0 # 数据库索引

--- #################### 定时任务相关配置 ####################
xxl:
  job:
    enabled: false # 本地开发关闭定时任务，按需调试开启

# 日志文件配置
logging:
  level:
    xyz.entdiy: DEBUG

--- #################### 框架相关配置 ####################
biz:
  captcha:
    enable: false # 本地环境，暂时关闭图片验证码，方便登录等接口的测试
  security:
    mock-enable: true
  access-log: # 访问日志的配置项
    enable: false
  error-code: # 错误码相关配置项
    enable: false
  env:
    # 各自开发人员可以设置为自己的姓名全拼，gateway优先路由tag匹配注册服务，调用本地运行应用
    tag: theMonkeyKing
