---
spring:
  security:
    user:
      name: "admin"
      password: "123456"

--- #################### Spring Boot Admin服务端的相关配置 ####################
spring:
  boot:
    admin:
      # Spring Boot Admin Server 服务端的相关配置
      context-path: /admin-boot
      # Spring Boot Admin Client 客户端的相关配置
      client:
        #以ip注册到admin server上，默认false使用hostname注册
        instance:
          service-host-type: IP # 注册实例时，优先使用 IP [IP, HOST_NAME, CANONICAL_HOST_NAME]
          prefer-ip: true
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}

--- #################### Druid Admin 相关配置 ####################
monitor:
  druid:
    contextPath: /druid
    loginUsername: ${spring.security.user.name}
    loginPassword: ${spring.security.user.password}
    #需要监控的服务名spring.application.name
    applications:
      - system-server
      - infra-server
      - bpm-server
      - report-server
      - iot-server
