--- #################### 数据库相关配置 ####################
spring:
  datasource:
    dynamic: # 多数据源配置
      primary: master
      datasource:
        master:
          name: somersault_cloud_iot
          url: jdbc:mysql://${MYSQL_MASTER_ADDR:192.168.1.200:3306}/${spring.datasource.dynamic.datasource.master.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
        slave: # 模拟从库，可根据自己需要修改
          name: somersault_cloud_iot
          url: jdbc:mysql://${MYSQL_SLAVE_ADDR:192.168.1.200:3306}/${spring.datasource.dynamic.datasource.slave.name}?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例

  # Redis 配置，开发环境直连单Redis实例，生产环境为Sentinel哨兵连接模式
  redis:
    host: ${REDIS_HOST:192.168.1.200}
    port: 6379 # 端口
    database: 0 # 数据库索引

--- #################### MQ 消息队列相关配置 ####################
spring:
  cloud:
    stream:
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: ${ROCKETMQ_ADDR:192.168.1.200:9876} # RocketMQ Namesrv 地址

--- #################### 定时任务相关配置 ####################

xxl:
  job:
    enabled: false # 是否开启调度中心，默认为 true 开启

# 日志文件配置
logging:
  level:
    xyz.entdiy: DEBUG

--- #################### 框架相关配置 ####################
biz:
  info:
    version: 2.0.0
  security:
    mock-enable: true
  access-log: # 访问日志的配置项
    enable: false
  error-code: # 错误码相关配置项
    enable: false
  env:
    # 各自开发人员可以设置为自己的姓名全拼，gateway优先路由tag匹配注册服务，调用本地运行应用
    tag: entdiy.xyz
